import { Injectable } from '@angular/core';
import { environment } from '../../../../environments/environment.prod'
import { HttpClient } from  '@angular/common/http';
import { Observable, BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class RestserviceService {
  public bookingdata: any = {};
  public orderdetails: any = {};  
  public astrologerData: any = {};
  public booking_slots: any = {};
  public pendindingappoint:any = {}; 

public BASE_URL:string;


public videocallOrderId:string;

  constructor(private http:HttpClient) { 
      this.BASE_URL = environment.BASE_URL;
    console.log("rajjjjjjjjjjjjj", this.videocallOrderId);
    }
  
  public  Get(url:string):Observable<any>{
  	console.log("datadddd",url);
      let fullurl:string =`${this.BASE_URL}${url}`;
      console.log("urll",fullurl);
    return this.http.get(fullurl);
  }

  public Post(url,data):Observable<any>{
  console.log("data",data);
    let fullurl:string = `${this.BASE_URL}${url}`
    return this.http.post(fullurl,data);
  }




messageSource = new BehaviorSubject('default message');
  currentMessage = this.messageSource.asObservable();

  changeMessage(message: any) {
    this.messageSource.next(message)
  }

  

 messageSource1= new BehaviorSubject('message');
  currentMessage1 = this.messageSource1.asObservable();
  changeMessage1(data: any) {
    console.log(data,"mmm");
    this.messageSource1.next(data)
  }



  public countryList1: Array<any> = [
     { name: 'Andhra Pradesh', cities: ['Anantapur',
                 'Chittoor',
                 'East Godavari',
                 'Guntur',
                 'Krishna',
                 'Kurnool',
                 'Prakasam',
                 'Sri Potti Sri Ramulu Nellore',
                 'Srikakulam',
                 'Visakhapatnam',
                 'Vizianagaram',
                 'West Godavari',
                 'YSR Kadapa',] },
     { name: 'Arunachal Pradesh', cities: ['Anjaw',
                 'Changlang',
                 'East Kameng',
                 'East Siang',
                 'Kamle',
                 'Kra Daadi',
                 'Kurung Kumey',
                 'Lohit',
                 'Longding',
                 'Lower Subansiri',
                 'Lower Siang',
                 'Lower Dibang Valley',
                 'Namsai',
                 'Papum Pare',
                 'Siang',
                 'Tawang',
                 'Tirap',
                 'Upper Dibang Valley',
                 'Upper Siang',
                 'Upper Subansiri',
                 'West Kameng',
                 'West Siang',] },
     { name: 'Assam', cities: ['Baksa',
                 'Barpeta',
                 'Biswanath',
                 'Bongaigaon',
                 'Cachar',
                 'Charaideo',
                 'Chirang',
                 'Darrang',
                 'Dhemaji',
                 'Dhubri',
                 'Dibrugarh',
                 'Dima Hasao',
                 'Goalpara',
                 'Golaghat',
                 'Hailakandi',
                 'Hojai',
                 'Jorhat',
                 'Kamrup Metropolitan',
                 'Kamrup',
                 'Karbi Anglong',
                 'Karimganj',
                 'Kokrajhar',
                 'Lakhimpur',
                 'Majuli',
                 'Morigaon',
                 'Nagaon',
                 'Nalbari',
                 'Sivasagar',
                 'Sonitpur',
                 'South Salmara-Mankachar',
                 'Tinsukia',
                 'Udalguri',
                 'West Karbi Anglong',] },
     { name: 'Bihar', cities: ['Araria',
                 'Arwal',
                 'Aurangabad',
                 'Banka',
                 'Begusarai',
                 'Bhagalpur',
                 'Bhojpur',
                 'Buxar',
                 'Darbhanga',
                 'East Champaran',
                 'Gaya',
                 'Gopalganj',
                 'Jamui',
                 'Jehanabad',
                 'Khagaria',
                 'Kishanganj',
                 'Kaimur',
                 'Katihar',
                 'Lakhisarai',
                 'Madhubani',
                 'Munger',
                 'Madhepura',
                 'Muzaffarpur',
                 'Nalanda',
                 'Nawada',
                 'Patna',
                 'Purnia',
                 'Rohtas ',
                 'Saharsa',
                 'Samastipur',
                 'Sheohar',
                 'Sheikhpura',
                 'Saran',
                 'Sitamarhi',
                 'Supaul',
                 'Siwan',
                 'Vaishali',
                 'West Champaran',] },
     { name: 'Chhattisgarh', cities: ['Balod',
                 'Baloda Bazar',
                 'Balrampur',
                 'Bastar',
                 'Bemetara',
                 'Bijapur',
                 'Bilaspur',
                 'Dantewada',
                 'Dhamtari',
                 'Durg',
                 'Gariaband',
                 'Janjgir-Champa',
                 'Jashpur',
                 'Kabirdham',
                 'Kanker',
                 'Kondagaon',
                 'Korba',
                 'Koriya',
                 'Mahasamund',
                 'Mungeli',
                 'Narayanpur',
                 'Raigarh',
                 'Raipur',
                 'Rajnandgaon',
                 'Sukma',
                 'Surajpur',
                 'Surguja',] },
     { name: 'Goa', cities: ['North Goa',
                 'South Goa',] },
     { name: 'Gujarat', cities: ['Ahmedabad',
                 'Amreli',
                 'Anand',
                 'Aravalli',
                 'Banaskantha',
                 'Bharuch',
                 'Bhavnagar',
                 'Botad',
                 'Chhota Udaipur',
                 'Dahod',
                 'Dang',
                 'Devbhoomi Dwarka',
                 'Gandhinagar',
                 'Gir Somnath',
                 'Jamnagar',
                 'Junagadh',
                 'Kutch',
                 'Kheda',
                 'Mahisagar',
                 'Mehsana',
                 'Morbi',
                 'Narmada',
                 'Navsari',
                 'Panchmahal',
                 'Patan',
                 'Porbandar',
                 'Rajkot',
                 'Sabarkantha',
                 'Surat',
                 'Surendranagar',
                 'Tapi',
                 'Vadodara',
                 'Valsad',] },
     { name: 'Haryana', cities: ['Ambala',
                 'Bhiwani',
                 'Charkhi Dadri',
                 'Faridabad',
                 'Fatehabad',
                 'Gurugram',
                 'Hisar',
                 'Jhajjar',
                 'Jind',
                 'Kaithal',
                 'Karnal',
                 'Kurukshetra',
                 'Mahendragarh',
                 'Nuh',
                 'Palwal',
                 'Panchkula',
                 'Panipat',
                 'Rewari',
                 'Gurgaon',
                 'Rohtak',
                 'Sirsa',
                 'Sonipat',
                 'Yamunanagar',] },
     { name: 'Himachal Pradesh', cities: ['Bilaspur',
                 'Chamba',
                 'Hamirpur',
                 'Kangra',
                 'Kinnaur',
                 'Kullu',
                 'Lahaul-Spiti',
                 'Mandi',
                 'Shimla',
                 'Solan',
                 'Sirmour',
                 'Una',] },
     { name: 'Jammu & Kashmir', cities: ['Anantnag District',
                 'Bandipora District',
                 'Baramulla District',
                 'Budgam District',
                 'Doda District',
                 'Ganderbal District',
                 'Jammu District',
                 'Kathua District',
                 'Kishtwar District',
                 'Kulgam District',
                 'Kupwara District',
                 'Kargil District',
                 'Leh District',
                 'Poonch District',
                 'Pulwama District',
                 'Rajouri District',
                 'Ramban District',
                 'Reasi District',
                 'Samba District',
                 'Shopian District',
                 'Srinagar District',
                 'Udhampur District',] },
     { name: 'Jharkhand', cities: ['Bokaro',
                 'Chatra',
                 'Deoghar',
                 'Dhanbad',
                 'Dumka',
                 'East Singhbhum(Jamshedpur)',
                 'Garhwa',
                 'Giridih',
                 'Godda',
                 'Gumla',
                 'Hazaribagh',
                 'Jamtara',
                 'Koderma',
                 'kunti',
                 'Latehar',
                 'Lohardaga',
                 'Palamu',
                 'Pakur',
                 'Ramgarh',
                 'Ranchi',
                 'Sahebganj',
                 'Simdega',
                 'Saraikela Kharsawan',
                 'West Singhbhum(Chaibasa)',] },
     { name: 'Karnataka', cities: ['Bagalkot',
                 'Bengaluru Rural',
                 'Bengaluru Urban',
                 'Belagavi',
                 'Ballari',
                 'Bidar',
                 'Chamarajanagar',
                 'Chikballapur',
                 'Chitradurga',
                 'Chikkamagalur',
                 'Chitradurga',
                 'Dakshina Kannada',
                 'Davanagare',
                 'Dharwad',
                 'Gadag',
                 'Hassan',
                 'Haveri',
                 'Kalaburagi',
                 'Kodagu',
                 'Kolar',
                 'Koppal',
                 'Mandya',
                 'Mysuru',
                 'Raichur',
                 'Ramanagara',
                 'Shivamogga',
                 'Tumakuru',
                 'Udupi',
                 'Uttara Kannada',
                 'Vijayapur',
                 'Yadgir',] },
     { name: 'Kerala', cities: ['Alapuzzha',
                 'Ernakulam',
                 'Idukki',
                 'Kannur',
                 'Kasaragod',
                 'Kollam',
                 'Kottayam',
                 'Kozhikode',
                 'Malappuram',
                 'Palakkad',
                 'Pathanamthitta',
                 'Thiruvananthapuram',
                 'Thrissur',
                 'Wayanad',] },
     { name: 'Madhya Pradesh', cities: ['Ashoknagar',
                 'Alirajpur',
                 'Anuppur',
                 'Agar Malwa',
                 'Barwani',
                 'Bhopal',
                 'Balaghat',
                 'Betul',
                 'Bhind',
                 'Burhanpur',
                 'Chhindwara',
                 'Chhattarpur',
                 'Datia',
                 'Dhar',
                 'Dindori',
                 'Damoh',
                 'Dewas',
                 'Gwalior',
                 'Guna',
                 'Harda',
                 'Hoshangabad',
                 'Indore',
                 'Jhabua',
                 'Jabalpur',
                 'Khandwa',
                 'Khargone',
                 'Katni',
                 'Morena',
                 'Mandla',
                 'Mandsaur',
                 'Neemuch',
                 'Panna',
                 'Raisen',
                 'Rajgarh',
                 'Rewa',
                 'Ratlam',
                 'Sindi',
                 'Satna',
                 'Shahdol',
                 'Sehore',
                 'Sagar',
                 'Seoni',
                 'Shivpuri',
                 'Shajapur',
                 'Sheopur',
                 'Singrauli',
                 'Umaria',
                 'Ujjain',
                 'Vidisha',] },
     { name: 'Maharashtra', cities: ['Aurangabad',

                 ' Bandra(Mumbai Suburban district)',
                 'Nagpur',
                 'Pune',
                 'Akola',
                 'Chandrapur',
                 'Jalgaon',
                 'Parbhani',
                 'Sholapur',
                 'Thane',
                 'Latur',
                 'Mumbai-City',
                 'Buldhana',
                 'Dhule',
                 'Kolhpur',
                 'Nanded',
                 'Raigad',
                 'Amravati',
                 'Nashik',
                 'Wardha',
                 'Ahmednagar',
                 'Beed',
                 'Bhandara',
                 'Gadchiroli',
                 'Jalna',
                 'Osmanabad',
                 'Ratnagiri',
                 'Sangli',
                 'Satara',
                 'Sindudurg',
                 'Yavatmal',
                 'Nandurbar',
                 'Washim',
                 'Gondia',
                 'Hingoli'] },
     { name: 'Manipur', cities: [' Imphal East',

                 ' Imphal West',
                 'Thoubal',
                 'Bishnupur',
                 'Chandel',
                 'Churachandpur',
                 'Senapati',
                 'Ukhrul',
                 'Tamenglong'] },
     { name: 'Meghalaya', cities: ['Ri-Bhoi District',

                 'South Garo Hills',
                 'East Khasi Hill',
                 'East Garo Hill',
                 'West Garo Hill',
                 'Jaintia Hill',
                 'West Khasi Hill'] },
     { name: 'Mizoram', cities: ['Luglei District',

                 'Chimtipui District',
                 'Aizawal',
                 'Champhai',
                 'Mamit',
                 'Kolasib',
                 'Serchhip',
                 'Lawngtlai'] },
     { name: 'Nagaland', cities: ['Wokha',

                 'Phek',
                 'Tuensang',
                 'Mon',
                 'Kohima',
                 'Zunheboto',
                 'Mokokchung',
                 'Dimapur' ]},
     { name: 'Odisha', cities: ['Khurda',
                 'Navaragpur',
                 'Navapada',
                 'Gajapati',
                 'Boudh',
                 'Bhadrak',
                 'Ganjam',
                 'Dhenkanal',
                 'Angul',
                 'Puri',
                 'Cuttak',
                 'Sambalpur',
                 'Kalhandi',
                 'Koraput',
                 'Phulbani',
                 'Balangir',
                 'Bargarh',
                 'Deogarh',
                 'Jagatsinghpur',
                 'Jajpur',
                 'Jharsuguda',
                 'Kendrapara',
                 'Malkangiri',
                 'Nayagarh',
                 'Rayagada',
                 'Sonepur',
                 'Balasore',
                 'Mayurbhanj',
                 'Keonjhar',
                 'Sundergarh'] },
     { name: 'Punjab', cities: ['Sangrur',

                 'Jalandhar',
                 'Ludhiana',
                 'Bhatinda',
                 'Kapurthala',
                 'Patiala',
                 'Amritsar',
                 'Ferozepur',
                 'Fatehgarh Saheb',
                 'Ropar',
                 'Gurdaspur',
                 'Hosiarpur',
                 'Faridkot',
                 'Mansa',
                 'Moga',
                 'Muktsar',
                 'Navansahar'] },
     { name: 'Rajasthan', cities: ['Jaipur',

                 'Barmer',
                 'Dungarpur',
                 'Jodhpur',
                 'Kota',
                 'Udaipur',
                 'Bikaner',
                 'Dausa',
                 'Bundi',
                 'Sikar',
                 'Tonk',
                 'Jaisalmer',
                 'Nagaur',
                 'Rajsamand',
                 'Banswara',
                 'Bhilwara',
                 'Ajmer',
                 'Alwar',
                 'Bharatpur',
                 'Chittorgarh',
                 'Churu',
                 'Dholpur',
                 'Ganganagar',
                 'Jalor',
                 'Jhalawar',
                 'Jhunjhunu',
                 'Pali',
                 'Sawai Madhopur',
                 'Sirohi',
                 'Baran',
                 'Hanumangarh',
                 'Karauli'] },
     { name: 'Sikkim', cities: ['East',

                 'South',
                 'West',
                 'North'] },
     { name: 'Tamil Nadu', cities: ['Chennai',

                 'Coimbotore',
                 'Cuddalorei',
                 'Dharmapuri',
                 'Dindigul',
                 'Erode',
                 'Kancheepuram',
                 'Kanniyakumari (HQ : Nagercoil)',
                 'Karur',
                 'Madurai',
                 'Nagapattinam',
                 'Namakkal',
                 'Nilgiris (HQ: Udhagamandalam)',
                 'Perambalur',
                 'Pudukkottai',
                 'Ramanathapuram',
                 'Salem',
                 'Sivaganga',
                 'Thanjavur',
                 'Theni',
                 'Thoothkudi',
                 'Tiruchiorappalli',
                 'Tirunelveli',
                 'Tiruvallur',
                 'Tiruvannamalai',
                 'Tiruvarur',
                 'Vellore',
                 'Villupuram',
                 'Virudhunagar'] },
     { name: 'Telangana', cities: ['Adilabad',
                 'Bhadradri Kothagudem',
                 'Hyderabad',
                 'Jagtial',
                 'Jangaon',
                 'Jayashankar Bhupalapally',
                 'Jogulamba Gadwal',
                 'Kamareddy',
                 'Karimnagar',
                 'Khammam',
                 'Kumarambheem Asifabad',
                 'Mahabubabad',
                 'Mahabubnagar',
                 'Mancherial',
                 'Medak',
                 'Medchal?Malkajgiri',
                 'Nagarkurnool',
                 'Nalgonda',
                 'Nirmal',
                 'Nizamabad',
                 'Peddapalli',
                 'Rajanna Sircilla',
                 'Ranga Reddy',
                 'Sangareddy',
                 'Siddipet',
                 'Suryapet',
                 'Vikarabad',
                 'Wanaparthy',
                 'Warangal Rural',
                 'Warangal Urban',
                 'Yadadri Bhuvanagiri'] },
     { name: 'Tripura', cities: [' North District',

                 'South District',
                 'West District',
                 'Dhalai District'] },
     { name: 'Uttar Pradesh', cities: ['Allahabad',

                 'Aligarh',
                 'Bareilly',
                 'Gonda',
                 'Hardoi',
                 'Kanpur Dehat',
                 'Ghaziabad',
                 'Unnav',
                 'Varanasi',
                 'Faizabad',
                 'Gorakpur',
                 'Jhansi',
                 'Lucknow',
                 'Agra',
                 'Meerut',
                 'Moradabad',
                 'Barabanki',
                 'Mainpuri',
                 'Etawah',
                 'Gazipur',
                 'Etah',
                 'Muzaffar Nagar',
                 'Saharanpur',
                 'Bulandshehar',
                 'Mathura',
                 'Firozabad',
                 'Budaun',
                 'Shahjahanpur',
                 'Pilibhit',
                 'Bijnor',
                 'Rampur',
                 'Kanpur(Nagar)',
                 'Farrukhabad',
                 'Fatehpur',
                 'Pratapgarh',
                 'Jalaun',
                 'Hamirpur',
                 'Lalitpur',
                 'Mirzapur',
                 'Basti',
                 'Deoria',
                 'Raebareili',
                 'Sitapur',
                 'Banda',
                 'Lakhimpur-Khedi',
                 'Bahraich',
                 'Sultanpur',
                 'Mau',
                 'Azamgarh',
                 'Jaunpur',
                 'Balia',
                 'Bhadoi',
                 'Padrauna',
                 'Maharajganj',
                 'Siddharth Nagar',
                 'Sunbhadra',
                 'Mahoba',
                 'Ambedkarnagar',
                 'Gautam Bodda Nagar',
                 'Maha Maya Nagar',
                 'jyotiba Phoole Nagar',
                 'Kaushambi',
                 'Shooji Maharaj',
                 'Chandauli',
                 'Balrampur',
                 'Shravati',
                 'Bagpat',
                 'Kanooj',
                 'Oraiyya',
                 'Sant Kabir Nagar'] },
     { name: 'Uttarakhand', cities: ['Nainital',

                 'Almora',
                 'Pitoragarh',
                 'Udhamsingh Nagar',
                 'Bageshwar',
                 'Champawat',
                 'Garhwal(Pauri)',
                 'Tehri-Garhwal',
                 'Chamoli( Gopeshwar )',
                 'Uttarkashi',
                 'Dehradun',
                 'Rudraprayag',
                 'Haridwar'] },
     { name: ' West Bengal', cities: ['Howrah',

                 'Darjeeling',
                 'Medinipur',
                 'Murshidabad',
                 'Coochbehar',
                 'Malda',
                 'Birbhum',
                 'North 24 Parganas',
                 'South 24 Parganas',
                 'Bankura',
                 'Bardhaman',
                 'Jalpaiguri',
                 'Hooghly',
                 'Nadia',
                 'Dakshin Dinajpur',
                 'Purulia',
                 'Uttar Dinajpur',
                 'Siliguri'] },
     { name: 'Andaman & Nicobar', cities: ['Andaman',

                 'Nicobar'] },
     { name: 'Chandigarh', cities: ['Chandigarh'] },
     { name: 'Dadra & Nagar Haveli', cities: ['Dadra'] },
     { name: 'Daman & Diu', cities: ['Dama',

                 'Diu'] },
     { name: 'Lakshadweep', cities: ['Lakshadweep'] },
     { name: 'NCT Delhi', cities: ['New Delhi',

                 'Central',
                 'North',
                 'North West',
                 'West',
                 'South West',
                 'North',
                 'North East'] },
     { name: 'Puducherry', cities: ['Karikal',

                 'Mahe',
                 'Yaman',
                 'Pondicherry']},

     ];}








